<a href="https://colab.research.google.com/github/Patelroneek/data-science-topics-/blob/main/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1d array
import numpy as np
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#2d array
b= np.array([[1, 2], [4, 5]])
print(b)

[[1 2]
 [4 5]]


In [ ]:
#3d array
c= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#ones_array
ones_array = np.ones((3,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#zeros_array
zeros_array = np.zeros((4,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#linespace
linspace_array = np.linspace(0, 100, 5)
print(linspace_array)

[  0.  25.  50.  75. 100.]


In [ ]:
#randn
rand_array = np.random.rand(3, 3)
print(rand_array)

[[0.70163555 0.82302213 0.57207219]
 [0.6655371  0.68117479 0.70566166]
 [0.70975825 0.31682451 0.91408714]]


In [ ]:
#randint
randint_array = np.random.randint(1, 100, (3, 3))
print(randint_array)

[[48 31 70]
 [35 46 82]
 [45 49 49]]


In [ ]:
#identity matrix
i=np.eye(4,4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#randn
randn_array = np.random.randn(3, 3)
print(randint_array)

[[48 31 70]
 [35 46 82]
 [45 49 49]]


In [ ]:
#reshape
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Maximum and minimum
import numpy as np

arr = np.array([1, 5, 2, 8, 3, 9, 4, 7, 6])

max_value = np.max(arr)
print("Maximum value:", max_value)

min_value = np.min(arr)
print("Minimum value:", min_value)

Maximum value: 9
Minimum value: 1


In [ ]:
# upper and lower triangular matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [ ]:
upper_triangular = np.triu(matrix)

In [ ]:
lower_triangular = np.tril(matrix)

In [ ]:
print(upper_triangular)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
print(lower_triangular)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
sum_of_triangles = upper_triangular + lower_triangular

In [ ]:
print(sum_of_triangles)

[[ 2  2  3]
 [ 4 10  6]
 [ 7  8 18]]


In [ ]:
# bmate
A = np.zeros((3, 3))
B = np.ones((3, 3))

combined_matrix = np.bmat([[A, B]])

print(combined_matrix)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [ ]:
# diagonal flat
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

diagonal = np.diag(matrix).flatten()

print(diagonal)

[1 5 9]


In [ ]:
#indexing
my_list = [1, 2, 3, 4, 5]

first_element = my_list[0]
print("First element:", first_element)

third_element = my_list[2]
print("Third element:", third_element)

last_element = my_list[-1]
print("Last element:", last_element)

First element: 1
Third element: 3
Last element: 5


In [ ]:
#slicing

sub_list = my_list[1:3]
print("Sub-list (1:3):", sub_list)

sub_list = my_list[:2]
print("Sub-list (:2):", sub_list)

sub_list = my_list[2:]
print("Sub-list (2:):", sub_list)

sub_list = my_list[::2]
print("Sub-list (::2):", sub_list)

Sub-list (1:3): [2, 3]
Sub-list (:2): [1, 2]
Sub-list (2:): [3, 4, 5]
Sub-list (::2): [1, 3, 5]


In [ ]:
#copy
# Original array
arr3 = np.array([1, 2, 3, 4, 5])

# Create a copy
arr4 = arr3.copy()

# Print both arrays
print("Original array:", arr3)
print("Copied array:", arr4)

Original array: [1 2 3 4 5]
Copied array: [1 2 3 4 5]


In [ ]:
#empty_like

# Create an example array
original_array = np.array([[1, 2], [4, 5]])

# Create an empty array with the same shape and type as the original array
empty_array = np.empty_like(original_array)

# Print the empty array
print(empty_array)

[[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]
